### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by sterlinm** [Quansight/terraform-jupyterhub#2]
Hi! I just wanted to politely and not demandingly ask about the status of this project. I noticed it a few months ago with excitement as I've been wanting to create something like this but felt a bit out of my depth. It's totally fine if it's on the backburner for whatever reason, but before going ahead and giving it a go myself I figured I'd make sure you're not going to release a vastly superior version two days later 😊.

Thanks!

**Comment by prasunanand** [comment]
Hi @sterlinm , I guess you are looking for https://github.com/Quansight/qhub-ops

**Comment by sterlinm** [comment]
Thanks so much!
